project_name: docker-mirror
env:
  - GO111MODULE=on
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - &build_default
    id: docker-mirror
    main: ./
    binary: docker-mirror-{{.Os}}-{{.Arch}}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

      - goarch: arm

  - <<: *build_default
    id: docker-mirror-arm
    goarch:
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    binary: docker-mirror-{{.Os}}-{{.Arch}}v{{.Arm}}

  - <<: *build_default
    id: pkg-docker-mirror
    no_unique_dist_dir: false
    binary: docker-mirror

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
    
checksum:
  name_template: checksums.txt

nfpms:
  - id: packages
    package_name: docker-mirror
    homepage: https://github.com/ChrisMcKee/docker-mirror
    maintainer: Chris McKee <pcdevils@gmail.com>
    description: Recursively formats a directory tree of nginx configs
    license: MIT
    bindir: /usr/bin
    builds:
      - pkg-docker-mirror
    formats:
      - apk
      - deb
      - rpm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - ^Merge

archives:
  - id: archive_binaries
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - docker-mirror

  - id: archive_default
    format: tar.gz
    builds:
      - pkg-docker-mirror
